### ISSUE TITLE
Release new version to fix test suite on OS X

### ISSUE THREAD

**Issue by mbrock** [seereason/process-extras#12]
A recent commit fixed the test to work on OS X (by replacing `echo -n` with `printf`). It would be good to bump the version and push this to Hackage.

**Comment by ddssff** [comment]
Ok, thanks for the reminder.

**Comment by ddssff** [comment]
Version 0.7.2 uploaded to hackage.

**Comment by mbrock** [comment]
:+1: Awesome, thanks!

I think from the reverse dependencies listing at http://packdeps.haskellers.com/reverse/process-extras that nothing depends on 0.7.1 specifically, so all reverse dependencies should just work now.

**Comment by ddssff** [comment]
That sounds optimistic, I like it!
