### ISSUE TITLE
Missing CHANGELOG file

### ISSUE THREAD

**Issue by asr** [seereason/process-extras#6]
A CHANGELOG file is missing in Hackage.

**Comment by ddssff** [comment]
No changelog file has ever been maintained for this package.  All we have is the git commits.  Therefore, I'm not sure how to best resolve this issue.

**Comment by asr** [comment]
Why not just start in version 0.3.6.6?

**Comment by ddssff** [comment]
ok

**Comment by asr** [comment]
Please remember to add a changelog.

**Comment by ddssff** [comment]
Done.

**Comment by ddssff** [comment]
Should I bump the version and upload to hackage?

**Comment by asr** [comment]
> Done.

I don't see the changelog in [this](https://github.com/seereason/process-extras/commit/300aebf8e4854c1c377d98e5a3c0b79939a4a838) commit.

**Comment by ddssff** [comment]
Ok, now for sure.

**Comment by asr** [comment]
> Should I bump the version and upload to hackage?

Why not just release 0.4.1.2 including [this]( https://github.com/seereason/process-extras/commit/15f8bf803bbdb0882e77c75176605fd7812f22f8) commit?

**Comment by asr** [comment]
Please wait before releasing...

**Comment by ddssff** [comment]
oops.  I'll do it again if you like.  What is the issue?

**Comment by asr** [comment]
> What is the issue?

You need to include the changelog file in the .cabal:

```
extra-source-files: changelog
```

**Comment by ddssff** [comment]
Ok.  I knew there was something...

**Comment by asr** [comment]
Please note you can use Hackage candidates (from http://hackage.haskell.org/):

Packages cannot be deleted, so you should consider uploading new versions packages as a [package candidate](http://hackage.haskell.org/packages/candidates/upload) and testing before publishing it to the main index.

**Comment by ddssff** [comment]
Oh, I was not aware of that.  Is it new?

**Comment by ddssff** [comment]
I decided the package is not high profile enough to justify a stay in the candidates section - I doubt anyone is going to test it.  And there are no operational changes in this version anyway, so I just uploaded 0.4.1.4 to the main repository.

**Comment by asr** [comment]
Thanks for adding the changelog and realising the new version.
