### ISSUE TITLE
Exception if process closes before all input has been written

### ISSUE THREAD

**Issue by Athas** [seereason/process-extras#8]
The following program crashes.  I believe this is because the process terminates before the entire input string has been written.  (You may need to fiddle with the size.)

```
{-# LANGUAGE OverloadedStrings #-}
import System.Process.Text (readProcessWithExitCode)
import qualified Data.Text as T

main :: IO ()
main = do
  (progCode, output, progerr) <-
    readProcessWithExitCode "/bin/false" [] a_ton_of_input
  print progCode
  print output
  print progerr
  where a_ton_of_input = T.pack $ replicate 100000 'a'
```

Result of execution:

```
$ ghc break-process.hs 
[1 of 1] Compiling Main             ( break-process.hs, break-process.o )
Linking break-process ...
$ ./break-process 
break-process: fd:4: hClose: resource vanished (Broken pipe)
```

**Comment by ddssff** [comment]
Well, the resource *did* vanish - maybe your code could catch and ignore that exception?  If so, I should put a note about it in the documentation, or even some option.  This happens a lot.

**Comment by ddssff** [comment]
`
{-# LANGUAGE OverloadedStrings #-}
import System.Process.Text (readProcessWithExitCode)

import qualified Data.Text as T
import System.Exit (ExitCode(ExitSuccess))
import GHC.IO.Exception (IOErrorType(ResourceVanished), IOException(ioe_type))
import Control.Exception (try, throw)

main :: IO ()
main = do
  (progCode, output, progerr) <-
    ignoreResourceVanished (ExitSuccess, "", "ignoring resource vanished exception")
      (readProcessWithExitCode "/bin/false" [] a_ton_of_input)
  print progCode
  print output
  print progerr
  where a_ton_of_input = T.pack $ replicate 100000 'a'

ignoreResourceVanished :: a -> IO a -> IO a
ignoreResourceVanished def action =
    try action >>= either ignoreResourceVanished' return
    where
      ignoreResourceVanished' e | ioe_type e == ResourceVanished = return def
      ignoreResourceVanished' e = throw e
`

**Comment by ddssff** [comment]
I wonder if there is any cleanup that needs to be done in readProcessWithExitCode when this happens?

**Comment by Athas** [comment]
With that workaround, I will lose anything that the process printed on its output channels before its demise.  This means that I cannot reliably launch a program that e.g. parses its standard input and prints an error message and terminates if it encounters a syntax error.  Well, I can, but the error message will be lost, which is not very useful.  I would expect that `readProcessWithExitCode` will never throw an exception due to the behaviour of the launched program.

With the workaround, the following non-error use will also return no output:

```
{-# LANGUAGE OverloadedStrings #-}
import System.Process.Text (readProcessWithExitCode)
import qualified Data.Text as T

main :: IO ()
main = do
  (progCode, output, progerr) <-
    readProcessWithExitCode "/usr/bin/head" [] a_ton_of_input
  print progCode
  print output
  print progerr
  where a_ton_of_input = T.pack $ replicate 100000 '\n'
```

**Comment by ddssff** [comment]
Yes, I see.  Let me think about this a bit.

**Comment by Athas** [comment]
I think that putting the workaround inside of `readProcessWithExitCode` itself, and simply returning the stdout and stderr contents is a fine solution.  The process does not terminate abnormally or anything of the sort, so you can get an exit code just fine.

**Comment by ddssff** [comment]
There actually is a call to ignoreResourceVanished inside of readCreateProcess, apparently the exception has slipped around it.

**Comment by ddssff** [comment]
I pushed a patch - please try it and let me know if it helps.

**Comment by Athas** [comment]
Seems to work!

**Comment by ddssff** [comment]
This matches changes already in System.Process, so I'm comfortable with it.
